### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by jourdain** [annehaley/trame-colormap-editor#15]
- [x] Tooltip over color bar
   - [x] flickering
   - [x] too big (help should be provided somewhere else)
   - [x] Missing hover color
   - [x] Some time the double click hit the tooltip and the action fails
- [x] The ui is too wide
   - [x] Control points (shown/select) takes too much space
   - [x] The filter range is too compact and unclear that it filter the table
- [x] Editing color
   - [x] Doesn't always edit the selected swatch
   - [x] Too sensitive (change the hue, panel disappear, need to click again to pick the color)
- [x] Reset full range on table filter not working
- [x] The panel for adjusting range works well but doesn't look good
- [x] Update/Apply seems disconnected from the UI (too much top margin) Should it be in the action row?

**Comment by annehaley** [comment]
>  Reset full range on table filter not working

@jourdain I am not able to replicate this one. Could you explain the behavior in more detail?

**Comment by annehaley** [comment]
Never mind, I found it and the fix for it. Each time I was setting `tableRange` to a _reference to_ `fullRange`, when it should have been a copy.

**Comment by annehaley** [comment]
> Update/Apply seems disconnected from the UI (too much top margin) Should it be in the action row?

Even better, we can get rid of this button and simply call update when the colorNode list is updated. That way each change to one or more nodes immediately propagates to the render sent to the color map.
